public enum Type {
    COMMENT,
    WHITESPACE,
    IDENTIFIER,
    OPERATOR,
    SEPARATOR,
    INT_LITERAL,
    FLOAT_LITERAL,
    CHAR_LITERAL,
    STRING_LITERAL,
    BOOLEAN_LITERAL,
    NULL_LITERAL,
    KEYWORD,
    ERROR
}
